export const GET_EMAILS = "GET_EMAILS";
export const LOADING_EMAIL = "LOADING_EMAIL";
export const LOADING_EMAIL_FROM_GMAIL = "LOADING_EMAIL_FROM_GMAIL";
export const SCANINNG_NEW_EMAILS = "SCANINNG_NEW_EMAILS";
export const DONE_SCANINNG_NEW_EMAILS = "DONE_SCANINNG_NEW_EMAILS";
